Repository European-XFEL/DAMNIT, pull requests merged in 2024-02, with the labels that each got.

#192 Refactor GUI table machinery
  damnit/gui/main_window.py
  damnit/gui/plot.py
  damnit/gui/table.py
  damnit/gui/user_variables.py
  tests/test_gui.py
Labels: GUI

#201 Fix call to get_column_states() while exporting to Zulip
  damnit/gui/main_window.py
  tests/test_gui.py
Labels: bug

#202 Fix filtering of disabled runs
  damnit/gui/table.py
  tests/test_backend.py
  tests/test_gui.py
Labels: bug

#204 Fix migration of old DataArray's
  damnit/migrations.py
Labels: bug

#206 Fix sorting by column in the GUI
  damnit/gui/table.py
Labels: bug

#207 Fix selecting rows for sending table to Zulip
  damnit/gui/table.py
Labels: bug

#209 Add the ability to pre-create runs in the database
  damnit/gui/main_window.py
  damnit/gui/table.py
  tests/test_gui.py
Labels: enhancement

#220 Skip over Variables returning unexpected types
  damnit/ctxsupport/ctxrunner.py
  tests/test_backend.py
Labels: bug
