Repository European-XFEL/DAMNIT, pull requests merged in 2024-01, with the labels that each got.

#170 Handle standalone comments properly
  damnit/gui/table.py
Labels: bug

#172 Add some (very) high-level docs for the data format
  docs/data-storage.md
  mkdocs.yml
Labels: documentation

#173 Fix a context file example
  docs/backend.md
Labels: documentation

#175 Fix the DPI calculation for creating thumbnails
  damnit/ctxsupport/ctxrunner.py
Labels: bug

#176 Add a migration for the short-lived intermediate v1 format
  damnit/cli.py
  damnit/migrations.py
Labels: enhancement

#177 Update deployment instructions
  README.md
Labels: documentation

#180 Add support for deleting variables
  damnit/backend/api.py
  damnit/backend/db.py
  damnit/gui/main_window.py
  damnit/gui/table.py
  tests/test_gui.py
Labels: enhancement

#187 Don't try to find max_diff from empty datasets
  damnit/migrations.py
Labels: bug
