Repository European-XFEL/DAMNIT, pull requests merged in 2025-02, with the labels that each got.

#379 FEAT: transient variables
  damnit/ctxsupport/ctxrunner.py
  damnit/ctxsupport/damnit_ctx.py
  docs/backend.md
  docs/changelog.md
  tests/test_backend.py
Labels: enhancement

#362 Basic row filtering
  damnit/gui/main_window.py
  damnit/gui/plot.py
  damnit/gui/standalone_comments.py
  damnit/gui/table.py
  damnit/gui/table_filter.py
  docs/changelog.md
  pyproject.toml
  tests/conftest.py
  tests/test_backend.py
  tests/test_gui.py
Labels: enhancement, GUI

#390 Don't pass DISPLAY environment variable to Slurm jobs
  damnit/backend/extraction_control.py
Labels: bug

#395 Catch errors producing thumbnail
  damnit/ctxsupport/ctxrunner.py
Labels: bug

#391 docs: fix meta argument name to get the proposal path.
  docs/backend.md
Labels: documentation

#398 Catch errors generating thumbnail from matplotlib Figure
  damnit/ctxsupport/ctxrunner.py
Labels: bug

#401 Fix thumbnail creation for `DataArray`'s with shape `(1, n)`
  damnit/ctxsupport/ctxrunner.py
  docs/changelog.md
  tests/test_backend.py
Labels: bug

#392 feat: column filter indicator
  damnit/gui/table.py
  docs/changelog.md
  tests/test_gui.py
Labels: GUI
